[project]
name = "language-laboratory"
version = "0.1.0"
description = "Experiment comparison of performance characteristics of different programming languages"
readme = "README.md"
requires-python = "==3.12.0"
dependencies = []
